name: 转换Clash配置并提交

on:
  push:
    paths:
      - "config.yml"
      - ".github/workflows/clash_config_convert.yml"
      - "clash/converter/global.js"
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 设置 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: 安装依赖
        run: npm install
        working-directory: ./clash/converter

      - name: 创建输出目录
        run: mkdir -p clash/converter/dist

      - name: 转换配置文件
        run: node clash/converter/convert.js config.yml clash/converter/dist/config_converted.yml

      - name: 提交转换后的文件
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add clash/converter/dist/config_converted.yml
          git diff --quiet && git diff --staged --quiet || git commit -m "🚀 自动更新转换后的配置文件"
          git push

      # - name: 刷新 CDN 缓存
      #   run: |
      #     BRANCH="${{ github.ref_name }}"
      #     curl -X GET "https://purge.jsdelivr.net/gh/JiangZhiyan00/clash_config@${BRANCH}/clash/converter/dist/config_converted.yml"
      #     curl -X GET "https://purge.jsdelivr.net/npm/JiangZhiyan00/clash_config@${BRANCH}/clash/converter/dist/config_converted.yml"
