name: clash配置更新邮件通知

on:
  push:
    branches:
      - main
      - jzy
      - libin
  pull_request:
    branches:
      - main
      - jzy
      - libin

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD

      # 将订阅邮箱文件内容保存为环境变量
      - name: Save Emails File Content as Environment Variable
        run: |
          echo "EMAIL_BRANCHES=$(cat subscribe/emails.txt)" >> $GITHUB_ENV

      # 将clash配置文件内容保存为环境变量
      - name: Save Clash Config File Content as Environment Variable
        run: |
          echo "CLASH_CONFIG_CONTENT=$(cat config/config.yml)" >> $GITHUB_ENV

      # 设置jdk
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 下载相关jar包
      - name: Download ai-code-review jar to libs directory
        run: |
          mkdir -p ./libs
          wget -O ./libs/clash-config-email-sender.jar https://github.com/JiangZhiyan00/clash-config-email-sender/releases/latest/download/clash-config-email-sender.jar

      # 执行邮件通知
      - name: Run Clash Config Email Sender
        run: java -Duser.timezone=Asia/Shanghai -jar ./clash-config-email-sender.jar
        # 设置一些环境变量
        env:
          # 必要
          BRANCH_NAME: ${{ GITHUB_REF_NAME }}
          EMAIL_BRANCHES: ${{ env.EMAIL_BRANCHES }}
          CLASH_CONFIG_CONTENT: ${{ env.CLASH_CONFIG_CONTENT }}
